basePath: /
definitions:
  main.GenerateResponse:
    properties:
      code:
        type: string
      expires_at:
        type: string
      generated_at:
        type: string
    type: object
  main.VerifyRequest:
    properties:
      code:
        type: string
      user_email:
        type: string
      user_id:
        type: string
    type: object
  main.VerifyResponse:
    properties:
      message:
        type: string
      valid:
        type: boolean
    type: object
host: localhost:8080
info:
  contact: {}
  description: This is a server for generating and verifying 2FA codes.
  title: 2FA Code Generator API
  version: "1.0"
paths:
  /code:
    get:
      consumes:
      - application/json
      description: Generates a new 6-digit code for a user, valid for a fixed 30-second
        UTC window.
      operationId: generate-code
      parameters:
      - description: User ID
        in: query
        name: userID
        required: true
        type: string
      - description: User Email
        in: query
        name: userEmail
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.GenerateResponse'
        "400":
          description: Bad Request
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
        "500":
          description: Internal Server Error
          schema:
            type: string
      summary: Generate a new 2FA code
  /verify:
    post:
      consumes:
      - application/json
      description: Verifies a 2FA code submitted by a user against the stored code
        for the current time window.
      operationId: verify-code
      parameters:
      - description: Verification Request
        in: body
        name: verificationRequest
        required: true
        schema:
          $ref: '#/definitions/main.VerifyRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.VerifyResponse'
        "400":
          description: Invalid request body
          schema:
            type: string
        "405":
          description: Method Not Allowed
          schema:
            type: string
      summary: Verify a 2FA code
swagger: "2.0"
